#! /usr/bin/env python
from vauxootools.vauxootools import VauxooToolsServers
from vauxootools.vauxootools import VxConfigServers
from vauxootools.instance import Instance


class ImportJournalsV6(object):
    '''
    Import journals from verion 6 of odoo
    '''

    def __init__(self, migration):
        '''
        @param migration: Object with origin and destiny conection
        '''
        self.migration = migration

    def create_sequence(self, a_type, company):
        '''
        Create the sequence in the destiny instance for the new journal
        @param a_type: Browse object of the sequence records in origin instance
        @param company: Integer with the id of main company for this record
        return the id of the new sequence
        '''
        if a_type:
            types = {
                'name': a_type.name,
                'company_id': company,
                'prefix': a_type.prefix,
                'suffix': a_type.suffix,
                'padding': a_type.padding,
                'number_increment': a_type.number_increment,
            }

            type_id = self.migration.dest.create('ir.sequence', types)
            return type_id

        return False

    def get_code(self, code, company):
        '''
        Send a new code for the journal because the journal code is unic
        @param code: String with the code of the new journal
        @param company: Integer with the company id in destiny instance
        return a string with unic code for the new journal
        '''
        account_ids = self.migration.dest.\
                                search('account.journal',
                                       [('code', '=', code),
                                        ('company_id', '=', company)])
        if account_ids:
            new_code = '%s-%s' %(code, 'R')
            return self.get_code(new_code, company)

        else:
            return code


    def get_account(self, account_brw, company):
        '''
        Search the corresponding account for the new journal in the destiny
        instance
        @param account_brw: Browse Object with the account record in the origin
                            instance
        @param company: Integer with the company id in the destiny instance
        return the id of the corresponding account in the destiny instance
        '''
        if account_brw:
            account_ids = self.migration.dest.\
                                 search('account.account',
                                        [('name', '=', account_brw.name),
                                         ('code', '=', account_brw.code),
                                         ('company_id', '=', company.id)])
            return account_ids and account_ids[0]

        return False

    def create_analytic(self, journal_brw, company):
        '''
        Create an analytic account for the new journal
        @param journal_brw: Browse object with the journal record
        @param company: Browse object with the main company record
        '''
        journal_ids = self.migration.dest.\
                             search('account.analytic.journal',
                                    [('name', '=', journal_brw.name),
                                     ('type', '=', journal_brw.type),
                                     ('code', '=', journal_brw.code),
                                     ('company_id', '=', company.id)])
        if journal_ids:
            return journal_ids[0]
        journal = {
            'name': journal_brw.name,
            'type': journal_brw.type,
            'code': journal_brw.code,
            'company_id': company.id,
            }

        self.migration.loger.info('Creating journal %s' % journal_brw.name)
        journal_id = self.migration.dest.create('account.analytic.journal',
                                                journal)
        return journal_id

    def create_journal(self, journal_brw, company):
        '''
        Create the new journal in the destiny instance
        @param journal_brw: Browse object with the journal record in the origin
                            instance
        @param company: Browse record with the company record in the destiny
                        instance
        '''
        journal_ids = self.migration.dest.\
                            search('account.journal',
                                   [('name', '=', journal_brw.name),
                                    ('code', '=', journal_brw.code),
                                    ('company_id', '=', company.id)])
        journal_id = False
        if journal_ids:
            return journal_ids[0]
        journal = {
            'name': journal_brw.name,
            'type': journal_brw.type,
            'code': self.get_code(journal_brw.code, company.id),
            'analytic_journal_id': \
                    journal_brw.analytic_journal_id and \
                        self.create_analytic(journal_brw.analytic_journal_id,
                                             company) or  False,
            'company_id': company.id,
            'currency_id': company.currency_id and company.currency_id.id,
            'sequence_id': self.create_sequence(journal_brw.sequence_id,
                                                company.id),
            'default_debit_account_id': \
                    self.get_account(journal_brw.default_debit_account_id,
                                     company),
            'default_credit_account_id': \
                    self.get_account(journal_brw.default_credit_account_id,
                                     company),
            }

        self.migration.loger.info('Creating journal %s' % journal_brw.name)
        try:
            journal_id = self.migration.dest.create('account.journal', journal)
        except Exception, problem:
            self.migration.loger.error('Error %s' % problem)
        return journal_id

    def main(self):
        '''
        Prepare the ids of the new records to create
        '''

        company_ids = self.migration.origin.search('res.company', [])
        company_id = company_ids and company_ids[0]
        company_dest = self.migration.dest.search('res.company', [])
        if company_id and company_dest:
            company_dest = self.migration.dest.browse('res.company',
                                                      company_dest[0])
            journal_ids = self.migration.origin.\
                                   search('account.journal',
                                          [('company_id', '=', company_id)])
            for journal in self.migration.origin.browse('account.journal',
                                                        journal_ids):
                self.create_journal(journal, company_dest)


class ImportAccountsV6(object):
    '''
    Import accounts from verion 6 of odoo
    '''

    def __init__(self, migration):
        '''
        @param migration: Object with origin and destiny conection
        '''
        self.migration = migration

    def import_account_type(self):
        '''
        Import the account type by import_data method way
        '''
        account_ids = self.migration.origin.\
                                    search('account.account.type',
                                           [])
        for account in self.migration.origin.execute('account.account.type',
                                                     'export_data',
                                                     account_ids,
                                                     ['id', 'name',
                                                      'code', 'report_type',
                                                      'close_method']
                                                    )['datas']:
            result = self.migration.dest.execute('account.account.type',
                                                 'import_data',
                                                 ['id', 'name',
                                                  'code', 'report_type',
                                                  'close_method'],
                                                 [account])
            if result[2]:
                self.migration.loger.error('Error creating the type %s '
                                           'because %s' % (account[1],
                                                           result[2]))
            else:
                self.migration.loger.info('Created the account type %s '
                                          '' % (account[1]))
        return True

    def main(self):
        '''
        Search the records to create in the new instance
        '''
        company_ids = self.migration.origin.search('res.company', [])
        company_id = company_ids and company_ids[0]
        company_dest = self.migration.dest.search('res.company',
                                                  [])
        if company_id and company_dest:
            self.import_account_type()
            company_dest = self.migration.dest.browse('res.company',
                                                      company_dest[0])
            account_ids = self.migration.origin.\
                                     search('account.account',
                                            [])
            for account in self.migration.origin.execute('account.account',
                                                         'export_data',
                                                         account_ids,
                                                         ['id', 'name',
                                                          'code',
                                                          'currency_id',
                                                          'parent_id/id',
                                                          'user_type/id']
                                                        )['datas']:

                result = self.migration.dest.execute('account.account',
                                                     'import_data',
                                                     ['id', 'name',
                                                      'code', 'currency_id',
                                                      'parent_id/id',
                                                      'user_type/id'],
                                                     [account])
                if result[2]:
                    self.migration.loger.error('Error creating the account %s '
                                               'because %s' % (account[1],
                                                               result[2]))
                else:
                    self.migration.loger.info('Created the account %s '
                                              '' % (account[1]))



class ImportPartnerV6(object):
    '''
    IMport partners from verion 6 of odoo
    '''

    def __init__(self, migration):
        '''
        @param migration: Object with origin and destiny conection
        '''
        self.migration = migration

    def get_account(self, account_brw, company):
        '''
        Get the partner account in destiny instance
        @param acount_brw: Browse object of the account record in origin
                           instance
        @param company: Browse record of the companuy in destiny instance
        return and id of the account found
        '''
        if account_brw:
            account_ids = self.migration.dest.search(
                'account.account', [('name', '=', account_brw.name),
                                    ('code', '=', account_brw.code),
                                    ('company_id', '=', company.id)])
            return account_ids and account_ids[0]

        return False

    def get_address_and_child(self, partner, address, company):
        '''
        Create contact for each partner address
        @param partner: Browse object with the partner in origin instance
        @param address: Browse record list with all res.partner.address
                        records of the partner to create
        @param company: Browse record of the companuy in destiny instance
        '''
        child = []
        partner_dict = {}
        invoice = False
        for i in address:
            if i.type == 'invoice' and not invoice:
                partner_dict.update({
                    'email': i.email,
                    'phone': i.phone,
                    'country_id': company.country_id and company.country_id.id,
                    'street': i.street,
                    'street2': i.street2,
                    'city': i.street2,
                    'mobile': i.mobile,
                    'fax': i.fax,
                    'type': i.type,
                })
                invoice = True

            else:
                child.append((0, 0, {
                    'name': i.name or 'Sin Nombre',
                    'email': i.email,
                    'property_account_payable': \
                             self.get_account(partner.property_account_payable,
                                              company),
                    'property_account_receivable': \
                         self.get_account(partner.property_account_receivable,
                                          company),
                    'phone': i.phone,
                    'country_id': company.country_id and company.country_id.id,
                    'street': i.street,
                    'street2': i.street2,
                    'city': i.street2,
                    'mobile': i.mobile,
                    'fax': i.fax,
                    'type': i.type,
                }))

        partner_dict.update({'child_ids': child})

        return partner_dict

    def create_partner(
            self,
            partner_brw,
            company):
        '''
        Create partner
        @param partner_brw: Browse object with the partner in origin instance
        @param company: Browse record of the companuy in destiny instance
        '''
        partner_id = False
        if partner_brw.vat:
            partner_ids = self.migration.dest.search('res.partner', [
                ('vat', '=', partner_brw.vat),
            ])
            if partner_ids:
                return partner_ids[0]
        partner = {
            'name': partner_brw.name or 'Sin Nombre',
            'vat': partner_brw.vat,
            'customer': partner_brw.customer,
            'is_company': True,
            'supplier': partner_brw.supplier,
            'company_id': company.id,
            'property_account_payable': self.get_account(
                partner_brw.property_account_payable,
                company),
            'property_account_receivable': self.get_account(
                partner_brw.property_account_receivable,
                company)}

        partner.update(
            self.get_address_and_child(
                partner_brw,
                partner_brw.address,
                company))
        partner_ids = self.migration.dest.search(
            'res.partner', [
                ('name', '=', partner_brw.name), ('vat', '=', partner.get(
                    'vat', False))])
        if partner_ids:
            return partner_ids[0]

        self.migration.loger.info('Creating partner %s' % partner_brw.name)
        try:
            partner_id = self.migration.dest.create('res.partner', partner)
        except Exception as problem:
            self.migration.loger.error('Error %s' % problem)
        return partner_id

    def main(self):
        '''
        Search record to create partners
        '''
        company_dest = self.migration.dest.search('res.company', [])
        company_dest = self.migration.dest.browse(
            'res.company',
            company_dest[0])
        partner_ids = self.migration.origin.search('res.partner', [], limit=50)
        for partner in partner_ids:
            partner = self.migration.origin.browse('res.partner', partner)
            self.create_partner(partner, company_dest)


class MigrationTools(object):
    '''
    Conections object to get records to migrate
    '''

    def __init__(self):
        '''
        Objects of origin and destiny
        '''
        self.origin = False
        self.dest = False
        self.loger = False

    def main(self, configuration):
        '''
        Get variables of the configuration object
        '''
        hostname = configuration.get_hostname()
        dbname = configuration.get_db()
        port = configuration.get_port()
        user = configuration.get_user()
        pwd = configuration.get_pwd()
        shost = configuration.get_shostname()
        sdb = configuration.get_sdb()
        sport = configuration.get_sport()
        suser = configuration.get_suser()
        spwd = configuration.get_spwd()
        origin = Instance(dbname=dbname, hostname=hostname, port=int(port),
                          passwd=pwd, username=user,
                          logger=configuration.logger)
        self.origin = origin.server_login()
        dest = Instance(dbname=sdb, hostname=shost, port=int(sport),
                        passwd=spwd, username=suser,
                        logger=configuration.logger)
        self.dest = dest.server_login()
        self.loger = configuration.logger
        return True



if __name__ == '__main__':

    CONFIGURATION = VauxooToolsServers(app_name='migrate_instances',
                                       usage_message="Created by VauxooTools",
                                       options=['dbname', 'hostname',
                                                'password', 'port', 'sd',
                                                'sh', 'spo', 'sp', 'su',
                                                'username'],
                                       log=True, vx_instance=VxConfigServers)

    CI = MigrationTools()
    CI.main(CONFIGURATION)
    ACCOUNT = ImportAccountsV6(CI)
    ACCOUNT.main()
